#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module XYZThrift
  class Merchant
    include ::Thrift::Struct, ::Thrift::Struct_Union
    ID = 1
    WEBSITE = 2
    NOTIFICATION_URL = 3
    ACTIVE = 4
    NAME = 5
    URL = 6
    BANK_MID = 7
    NOTIFICATION_EMAIL = 8
    INDUSTRY = 9

    FIELDS = {
      ID => {:type => ::Thrift::Types::STRING, :name => 'id'},
      WEBSITE => {:type => ::Thrift::Types::STRING, :name => 'website'},
      NOTIFICATION_URL => {:type => ::Thrift::Types::STRING, :name => 'notification_url'},
      ACTIVE => {:type => ::Thrift::Types::BOOL, :name => 'active'},
      NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
      URL => {:type => ::Thrift::Types::STRING, :name => 'url'},
      BANK_MID => {:type => ::Thrift::Types::STRING, :name => 'bank_mid'},
      NOTIFICATION_EMAIL => {:type => ::Thrift::Types::STRING, :name => 'notification_email'},
      INDUSTRY => {:type => ::Thrift::Types::STRING, :name => 'industry'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Transaction
    include ::Thrift::Struct, ::Thrift::Struct_Union
    ID = 1
    TRANSACTION_TIME = 2
    MERCHANT_ID = 3
    BANK_MID = 4
    GROSS_AMOUNT = 5
    CUSTOMER_NAME = 6
    CUSTOMER_EMAIL = 7
    STATUS = 8

    FIELDS = {
      ID => {:type => ::Thrift::Types::STRING, :name => 'id'},
      TRANSACTION_TIME => {:type => ::Thrift::Types::STRING, :name => 'transaction_time', :optional => true},
      MERCHANT_ID => {:type => ::Thrift::Types::STRING, :name => 'merchant_id', :optional => true},
      BANK_MID => {:type => ::Thrift::Types::STRING, :name => 'bank_mid', :optional => true},
      GROSS_AMOUNT => {:type => ::Thrift::Types::I32, :name => 'gross_amount', :optional => true},
      CUSTOMER_NAME => {:type => ::Thrift::Types::STRING, :name => 'customer_name', :optional => true},
      CUSTOMER_EMAIL => {:type => ::Thrift::Types::STRING, :name => 'customer_email', :optional => true},
      STATUS => {:type => ::Thrift::Types::STRING, :name => 'status', :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class MerchantNotFound < ::Thrift::Exception
    include ::Thrift::Struct, ::Thrift::Struct_Union
    def initialize(message=nil)
      super()
      self.reason = message
    end

    def message; reason end

    REASON = 1

    FIELDS = {
      REASON => {:type => ::Thrift::Types::STRING, :name => 'reason'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end
